name = "cederic-woy-former-worker"
main = "src/index.js"
compatibility_date = "2026-06-09"

[[kv_namespaces]]
binding = "LEVELS_KV"
id = "c0fd083783704e59a6ff267ce223cfd4" 

[durable_objects]
bindings = [
  { name = "MULTIPLAYER_ROOM", class_name = "MultiplayerRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["MultiplayerRoom"]
